

import java.awt.image.BufferedImage;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class JMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form JMainFrame
     */
    BufferedImage img = null;
    public JMainFrame() {
          
             initComponents();
             max.setEnabled(true);
            min.setEnabled(true);
            avg.setEnabled(true);
            gray.setEnabled(true);
            kdiv_proba.setEnabled(true);
             setDefaultCloseOperation(JMainFrame.DO_NOTHING_ON_CLOSE);
            
           
            
        } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        max = new javax.swing.JTextField();
        avg = new javax.swing.JTextField();
        kdiv_proba = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();
        min = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        kDivProbi = new javax.swing.JTextPane();
        gray = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        yellow = new javax.swing.JTextField();
        Orange = new javax.swing.JTextField();
        green = new javax.swing.JTextField();
        red = new javax.swing.JTextField();
        blue = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainfon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cut surface evaluation of white brined cheese in HSI");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(731, 300));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        getContentPane().setLayout(null);

        max.setEditable(false);
        max.setMinimumSize(new java.awt.Dimension(8, 20));
        max.setPreferredSize(new java.awt.Dimension(8, 20));
        max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //maxActionPerformed(evt);
            }
        });
        getContentPane().add(max);
        max.setBounds(200, 20, 51, 33);

        avg.setEditable(false);
        avg.setMinimumSize(new java.awt.Dimension(8, 20));
        avg.setPreferredSize(new java.awt.Dimension(8, 20));
        getContentPane().add(avg);
        avg.setBounds(200, 120, 51, 33);

        kdiv_proba.setEditable(false);
        kdiv_proba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //kdiv_probaActionPerformed(evt);
            }
        });
        getContentPane().add(kdiv_proba);
        kdiv_proba.setBounds(200, 220, 51, 33);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("kDiv White Avg");
        jLabel5.setToolTipText("");
        jLabel5.setMaximumSize(new java.awt.Dimension(90, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(90, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 14));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 150, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("kDiv Blue Avg");
        jLabel6.setMaximumSize(new java.awt.Dimension(80, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 200, 100, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("kDiv Orange Avg");
        jLabel7.setMaximumSize(new java.awt.Dimension(80, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 50, 120, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("kDiv Gray Avg");
        jLabel8.setMaximumSize(new java.awt.Dimension(80, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 200, 110, 20);

        jProgressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBar.setStringPainted(true);
        getContentPane().add(jProgressBar);
        jProgressBar.setBounds(5, 257, 718, 15);

        min.setEditable(false);
        min.setMinimumSize(new java.awt.Dimension(8, 20));
        min.setPreferredSize(new java.awt.Dimension(8, 20));
        getContentPane().add(min);
        min.setBounds(200, 70, 51, 34);

        kDivProbi.setEditable(false);
        jScrollPane2.setViewportView(kDivProbi);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(310, 10, 410, 242);

        gray.setEditable(false);
        getContentPane().add(gray);
        gray.setBounds(200, 170, 51, 33);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("kDiv Light  Gray Avg");
        jLabel9.setMaximumSize(new java.awt.Dimension(80, 14));
        jLabel9.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 100, 130, 20);

        yellow.setEditable(false);
        yellow.setMinimumSize(new java.awt.Dimension(8, 20));
        yellow.setPreferredSize(new java.awt.Dimension(8, 20));
        yellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //yellowActionPerformed(evt);
            }
        });
        getContentPane().add(yellow);
        yellow.setBounds(60, 20, 51, 33);

        Orange.setEditable(false);
        Orange.setMinimumSize(new java.awt.Dimension(8, 20));
        Orange.setPreferredSize(new java.awt.Dimension(8, 20));
        Orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //OrangeActionPerformed(evt);
            }
        });
        getContentPane().add(Orange);
        Orange.setBounds(60, 70, 51, 33);

        green.setEditable(false);
        green.setMinimumSize(new java.awt.Dimension(8, 20));
        green.setPreferredSize(new java.awt.Dimension(8, 20));
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //greenActionPerformed(evt);
            }
        });
        getContentPane().add(green);
        green.setBounds(60, 120, 51, 33);

        red.setEditable(false);
        red.setMinimumSize(new java.awt.Dimension(8, 20));
        red.setPreferredSize(new java.awt.Dimension(8, 20));
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //redActionPerformed(evt);
            }
        });
        getContentPane().add(red);
        red.setBounds(60, 170, 51, 33);

        blue.setEditable(false);
        blue.setMinimumSize(new java.awt.Dimension(8, 20));
        blue.setPreferredSize(new java.awt.Dimension(8, 20));
        blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //blueActionPerformed(evt);
            }
        });
        getContentPane().add(blue);
        blue.setBounds(60, 220, 51, 33);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("kDiv Black Avg");
        jLabel10.setMaximumSize(new java.awt.Dimension(80, 14));
        jLabel10.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(180, 0, 100, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("kDiv Dark Gray Avg");
        jLabel11.setMaximumSize(new java.awt.Dimension(80, 14));
        jLabel11.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel11.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 50, 130, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("kDiv Yellow Avg");
        jLabel12.setMaximumSize(new java.awt.Dimension(80, 14));
        jLabel12.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel12.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 100, 100, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("kDiv Red Avg");
        jLabel13.setMaximumSize(new java.awt.Dimension(80, 14));
        jLabel13.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel13.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 150, 100, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("kDiv Green Avg");
        jLabel14.setMaximumSize(new java.awt.Dimension(80, 14));
        jLabel14.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel14.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 0, 100, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("<html><br>G<br/><br>r<br/><br>a<br/><br>y<br/><br>s<br/><br>c<br/><br>a<br/><br>l<br/><br>e<br/></html>");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 0, 10, 250);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("<html><br>R<br/><br>G<br/><br>B<br/></html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 14, 120);

        mainfon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/443_70%opacity.jpg"))); // NOI18N
        mainfon.setAlignmentY(0.0F);
        getContentPane().add(mainfon);
        mainfon.setBounds(0, 0, 740, 270);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kdiv_probaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdiv_probaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdiv_probaActionPerformed

    private void maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxActionPerformed

    

    
    private JFileChooser chooser;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JMainFrame().setVisible(true);
                jStart.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JTextField Orange;
    static javax.swing.JTextField avg;
    static javax.swing.JTextField blue;
    public static javax.swing.JTextField gray;
    static javax.swing.JTextField green;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    static javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane2;
    static javax.swing.JTextPane kDivProbi;
    public static javax.swing.JTextField kdiv_proba;
    private javax.swing.JLabel mainfon;
    static javax.swing.JTextField max;
    static javax.swing.JTextField min;
    static javax.swing.JTextField red;
    static javax.swing.JTextField yellow;
    // End of variables declaration//GEN-END:variables

    private static JFrame jStart = new JStartFrame();
    
}
